name: "bluebell"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2024-01-01"
machine_id: 1

log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "bluebell"
  password: "bluebell"
  db_name: "bluebell"
  max_idle_conn: 100
  max_open_conn: 200

redis:
  host: "127.0.0.1"
  post: 6379
  password: ""
  db: 0
  pool_size: 100